#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
trade_lifecycle.py — Institutional Trade Lifecycle & Execution Management Engine
================================================================================
Specialized for Indian Equities (NSE Cash Delivery).
Implements:
  1. Position Sizing & Initial Risk Engine (1% Portfolio Risk, 5-7% ATR stop, 15% Exposure Cap).
  2. Asymmetric Two-Tier Profit Booking & Dynamic Trailing Stop State Machine:
       - State 0: OPEN (PnL < +15%) -> Initial Stop (tightened to -4% in defensive regimes).
       - State 1: RISK_FREE (PnL +12% to +15%) -> Ratchet to Breakeven + buffer (Entry * 1.015).
       - State 2: BANK_AND_TRAIL (PnL +20% to +25%) -> Bank 40% partial profit (>=3R), ratchet 60% runner stop to +10%.
       - State 3: POWER_RUNNER (Runner PnL > +25%) -> Dynamic exit:
           a) Primary Trend: Close < rising 50 SMA on volume (with 1-day low-volume grace).
           b) Climax Reversal: Close < 20 EMA when CMP / 50 SMA > 1.35.
           c) Blow-Off Exhaustion: CMP / 200 SMA > 1.70 AND range > 3x ATR14 AND 20d max volume.
  3. Real-World NSE Microstructure Guardrails:
       - 2% and 5% circuit band disqualification.
       - Distance to lower circuit (<= 1.5% risk warning).
       - Circuit-lock fallback protocol (suppress repeated cancels, queue pre-market AMO).
       - ₹5.0 Crore turnover floor and 1.5% turnover participation cap.
       - Nifty 500 macro regime governor.
"""

from __future__ import annotations
import math
import logging
from enum import Enum
from dataclasses import dataclass, field
from typing import Optional, Tuple, Dict, Any, List

logger = logging.getLogger("TradeLifecycleManager")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


class TradeState(str, Enum):
    """Explicit Lifecycle States for Active Momentum Positions."""
    STATE_0_OPEN = "OPEN"                      # Unrealized PnL < +15%
    STATE_1_RISK_FREE = "RISK_FREE"            # Unrealized PnL +12% to +15% (Stop at +1.5% BE)
    STATE_2_BANK_AND_TRAIL = "BANK_AND_TRAIL"  # Unrealized PnL +20% to +25% (40% Banked, Stop +10%)
    STATE_3_POWER_RUNNER = "POWER_RUNNER"      # 60% Runner > +25% PnL (Dynamic Trend Trail)
    STATE_CLOSED = "CLOSED"                    # Fully liquidated


class OrderAction(str, Enum):
    """Order routing actions generated by the execution engine."""
    INITIAL_BUY = "INITIAL_BUY"
    HOLD = "HOLD"
    PARTIAL_PROFIT = "PARTIAL_PROFIT"          # 40% partial take-profit
    FULL_CLOSE = "FULL_CLOSE"                  # Complete liquidation
    AMO_FALLBACK = "AMO_FALLBACK"              # Circuit-locked queue fallback order


class ExitReason(str, Enum):
    """Institutional exit trigger classifications."""
    NONE = "NONE"
    INITIAL_STOP = "INITIAL_STOP"                            # Hit initial -5% to -7% stop
    TIGHTENED_REGIME_STOP = "TIGHTENED_REGIME_STOP"          # Hit -4% stop during defensive regime
    BREAKEVEN_STOP = "BREAKEVEN_STOP"                        # Hit +1.5% breakeven floor
    LOCKED_PROFIT_STOP = "LOCKED_PROFIT_STOP"                # Hit +10% runner floor
    PRIMARY_TREND_50SMA = "PRIMARY_TREND_50SMA"              # Confirmed close below 50 SMA
    CLIMAX_MEAN_REVERSION_20EMA = "CLIMAX_EMA20"             # CMP > 1.35x 50 SMA and close < 20 EMA
    BLOWOFF_EXHAUSTION = "BLOWOFF_EXHAUSTION"                # CMP > 1.70x 200 SMA + 3x ATR bar + 20d peak vol
    CIRCUIT_LOCK_STOP = "CIRCUIT_LOCK_STOP"                  # Lower circuit lock liquidation
    ROTATION_TARGET = "ROTATION_TARGET"                      # Fixed-target rotation: sell & redeploy proceeds
    EMERGENCY_MANUAL = "EMERGENCY_MANUAL"


class MacroRegime(str, Enum):
    """Broader market regime determined from benchmark (Nifty 500 / MidSmallcap 400)."""
    BULL_MARKET = "BULL_MARKET"                # Benchmark > 50 SMA > 200 SMA
    CORRECTION_WATCH = "CORRECTION_WATCH"      # Benchmark > 200 SMA, but < 50 SMA
    DEFENSIVE_CASH = "DEFENSIVE_CASH"          # Benchmark < 200 SMA (No new buys, tight stops)


@dataclass
class MarketBar:
    """Current session bar and indicator metadata for a specific security."""
    symbol: str
    cmp: float
    open: float
    high: float
    low: float
    close: float
    volume: float
    atr_14: float
    sma_20: float
    sma_50: float
    sma_50_prev: float
    sma_150: float
    sma_200: float
    ema_20: float
    vol_sma_20: float
    vol_max_20: float
    turnover_20d: float                       # In ₹ (INR)
    lower_circuit: Optional[float] = None
    upper_circuit: Optional[float] = None
    circuit_band_pct: Optional[float] = None  # e.g., 0.02, 0.05, 0.10, 0.20
    is_fno: bool = False                      # True if stock trades in derivatives (dynamic bands)


@dataclass
class Position:
    """Active trade position state container."""
    symbol: str
    entry_price: float
    entry_date: str
    total_shares: int
    current_shares: int
    banked_shares: int = 0
    banked_pnl_rupees: float = 0.0
    current_stop: float = 0.0
    initial_stop_price: float = 0.0
    initial_stop_pct: float = 0.07
    state: TradeState = TradeState.STATE_0_OPEN
    peak_price: float = 0.0
    days_below_sma50: int = 0
    is_circuit_locked: bool = False
    queued_amo: bool = False
    order_history: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class OrderSignal:
    """Execution signal produced by the TradeLifecycleManager."""
    symbol: str
    action: OrderAction
    shares: int
    limit_price: float
    stop_loss: float
    reason: ExitReason | str
    urgency: str                              # "IMMEDIATE", "END_OF_DAY", "PRE_MARKET_AMO"
    metadata: Dict[str, Any] = field(default_factory=dict)


class TradeLifecycleManager:
    """
    Institutional Trade Lifecycle Manager & NSE Execution Engine.
    Handles position sizing, state machine transitions, dynamic trailing exits,
    circuit band protections, and liquidity checks.
    """

    def __init__(
        self,
        portfolio_equity: float = 100000.0,
        risk_per_trade_pct: float = 0.01,
        max_exposure_pct: float = 0.15,
        max_turnover_participation: float = 0.015,
        min_turnover_floor: float = 50000000.0,    # ₹5.0 Crore floor
        be_buffer_pct: float = 0.015,              # +1.5% covers STT, turnover, stamp duty
        partial_bank_pct: float = 0.40,            # 40% partial exit at Stage 2
        runner_stop_floor_pct: float = 0.10,       # +10% locked stop on remaining 60% runner
        climax_extension_mult: float = 1.35,       # CMP / 50 SMA > 1.35
        blowoff_sma200_mult: float = 1.70,         # CMP / 200 SMA > 1.70
        blowoff_range_atr_mult: float = 3.0,       # Daily range > 3x ATR14
        rotation_target_pct: Optional[float] = None  # Fixed-target rotation exit (e.g. 0.15); None = two-tier mode
    ):
        self.portfolio_equity = float(portfolio_equity)
        self.risk_per_trade_pct = float(risk_per_trade_pct)
        self.max_exposure_pct = float(max_exposure_pct)
        self.max_turnover_participation = float(max_turnover_participation)
        self.min_turnover_floor = float(min_turnover_floor)
        self.be_buffer_pct = float(be_buffer_pct)
        self.partial_bank_pct = float(partial_bank_pct)
        self.runner_stop_floor_pct = float(runner_stop_floor_pct)
        self.climax_extension_mult = float(climax_extension_mult)
        self.blowoff_sma200_mult = float(blowoff_sma200_mult)
        self.blowoff_range_atr_mult = float(blowoff_range_atr_mult)
        self.rotation_target_pct = float(rotation_target_pct) if rotation_target_pct is not None else None

    # ─────────────────────────────────────────────────────────────────────────
    # 1. POSITION SIZING & INITIAL RISK ENGINE
    # ─────────────────────────────────────────────────────────────────────────
    def calculate_initial_risk_and_size(
        self,
        cmp: float,
        atr_14: float,
        turnover_20d: float,
        regime: MacroRegime = MacroRegime.BULL_MARKET,
        circuit_band_pct: Optional[float] = None,
        is_fno: bool = False
    ) -> Tuple[int, float, float, Dict[str, Any]]:
        """
        Calculates position sizing according to institutional 1% risk rules:
          R = Portfolio Equity * 0.01
          Stop Distance = min(7%, max(5%, 2 * ATR_14 / CMP))
          In ₹: Stop Distance (₹) = CMP * Stop Distance %
          Raw Shares = floor(R / Stop Distance (₹))
          Capped by 15% Portfolio Equity Ceiling
          Capped by 1.5% of 20-Day Average Daily Turnover
          Defensive Regime adjusts initial stop floor to 4%.

        Returns: (shares, stop_price, stop_distance_pct, audit_meta)
        """
        if cmp <= 0:
            raise ValueError(f"Invalid CMP: {cmp}")

        # 1. 1% Portfolio Risk Budget
        risk_budget = self.portfolio_equity * self.risk_per_trade_pct

        # 2. Stop Distance = min(7%, max(5%, 2 * ATR14 / CMP))
        # In DEFENSIVE_CASH regime, tighten stop distance to 4%
        atr_pct = (2.0 * atr_14) / cmp if cmp > 0 else 0.06
        base_stop_dist = min(0.07, max(0.05, atr_pct))
        stop_dist_pct = min(0.04, base_stop_dist) if regime == MacroRegime.DEFENSIVE_CASH else base_stop_dist

        # Stop distance in INR
        stop_dist_inr = round(cmp * stop_dist_pct, 2)
        initial_stop_price = round(cmp - stop_dist_inr, 2)

        # Disallow new buys if Macro Regime is DEFENSIVE_CASH
        if regime == MacroRegime.DEFENSIVE_CASH:
            return 0, initial_stop_price, stop_dist_pct, {
                "allowed": False,
                "reason": "REGIME_FORBIDDEN: Benchmark < 200 SMA. Cash preservation active.",
                "initial_stop_price": initial_stop_price,
                "stop_distance_pct": round(stop_dist_pct * 100, 2)
            }

        # Liquidity Check
        if turnover_20d < self.min_turnover_floor:
            return 0, initial_stop_price, stop_dist_pct, {
                "allowed": False,
                "reason": f"LIQUIDITY_DISQUALIFIED: 20d Turnover ₹{turnover_20d:,.0f} < ₹{self.min_turnover_floor:,.0f} floor.",
                "initial_stop_price": initial_stop_price,
                "stop_distance_pct": round(stop_dist_pct * 100, 2)
            }

        # Circuit Band Check: Disqualify 2% and 5% circuit bands
        if not is_fno and circuit_band_pct is not None:
            normalized_band = circuit_band_pct if circuit_band_pct < 1.0 else circuit_band_pct / 100.0
            if normalized_band <= 0.051:
                return 0, initial_stop_price, stop_dist_pct, {
                    "allowed": False,
                    "reason": f"CIRCUIT_BAND_DISQUALIFIED: Band {normalized_band*100:.0f}% poses lower-circuit lockup risk.",
                    "initial_stop_price": initial_stop_price,
                    "stop_distance_pct": round(stop_dist_pct * 100, 2)
                }

        # 3. Allowable Shares from Risk
        raw_shares = math.floor(risk_budget / max(stop_dist_inr, 0.01))

        # 4. Cap by Maximum Position Exposure (10% to 15% equity)
        max_capital_for_pos = self.portfolio_equity * self.max_exposure_pct
        max_shares_exposure = math.floor(max_capital_for_pos / cmp)

        # 5. Cap by Liquidity Participation (max 1.5% of 20-day average daily turnover)
        max_liquidity_capital = turnover_20d * self.max_turnover_participation
        max_shares_liquidity = math.floor(max_liquidity_capital / cmp)

        # Constrain shares
        final_shares = min(raw_shares, max_shares_exposure, max_shares_liquidity)

        # Retail / small capital fallback: ensure at least 1 share if equity allows purchase
        if final_shares == 0 and cmp <= (self.portfolio_equity - 26.0):
            # Only allow 1 share if risk budget is within 10% tolerance for micro accounts
            final_shares = 1

        allocated_capital = round(final_shares * cmp, 2)
        portfolio_exposure_pct = round((allocated_capital / self.portfolio_equity) * 100, 2) if self.portfolio_equity > 0 else 0.0
        effective_risk_pct = round(((final_shares * stop_dist_inr) / self.portfolio_equity) * 100, 3) if self.portfolio_equity > 0 else 0.0

        audit_meta = {
            "allowed": final_shares > 0,
            "risk_budget_inr": round(risk_budget, 2),
            "stop_distance_pct": round(stop_dist_pct * 100, 2),
            "stop_distance_inr": stop_dist_inr,
            "initial_stop_price": initial_stop_price,
            "raw_risk_shares": raw_shares,
            "exposure_cap_shares": max_shares_exposure,
            "liquidity_cap_shares": max_shares_liquidity,
            "final_shares": final_shares,
            "allocated_capital": allocated_capital,
            "portfolio_exposure_pct": portfolio_exposure_pct,
            "effective_risk_pct": effective_risk_pct,
            "turnover_participation_pct": round((allocated_capital / turnover_20d) * 100, 3) if turnover_20d > 0 else 0.0
        }

        return final_shares, initial_stop_price, stop_dist_pct, audit_meta

    # ─────────────────────────────────────────────────────────────────────────
    # 2. NSE MARKET MICROSTRUCTURE & CIRCUIT GUARDRAILS
    # ─────────────────────────────────────────────────────────────────────────
    def check_liquidity_and_circuit(
        self,
        cmp: float,
        turnover_20d: float,
        circuit_band_pct: Optional[float] = None,
        lower_circuit: Optional[float] = None,
        upper_circuit: Optional[float] = None,
        is_fno: bool = False
    ) -> Dict[str, Any]:
        """
        Evaluates liquidity compliance and circuit band proximity risks.
        Returns safety diagnostics and risk flags.
        """
        diagnostics = {
            "liquidity_passed": turnover_20d >= self.min_turnover_floor,
            "turnover_crores": round(turnover_20d / 10000000.0, 2),
            "band_eligible": True,
            "circuit_band_pct": circuit_band_pct,
            "near_lower_circuit": False,
            "near_upper_circuit": False,
            "distance_to_lower_circuit_pct": None,
            "distance_to_upper_circuit_pct": None,
            "execution_risk_flag": False,
            "risk_notes": []
        }

        # Check circuit band eligibility
        if not is_fno and circuit_band_pct is not None:
            norm_band = circuit_band_pct if circuit_band_pct < 1.0 else circuit_band_pct / 100.0
            if norm_band <= 0.051:
                diagnostics["band_eligible"] = False
                diagnostics["risk_notes"].append(f"Restricted price band ({norm_band*100:.0f}%). High circuit trap risk.")

        # Check proximity to lower circuit
        if lower_circuit is not None and lower_circuit > 0:
            dist_lower_pct = (cmp - lower_circuit) / lower_circuit
            diagnostics["distance_to_lower_circuit_pct"] = round(dist_lower_pct * 100, 2)
            if dist_lower_pct <= 0.015:  # Within 1.5% of lower circuit
                diagnostics["near_lower_circuit"] = True
                diagnostics["execution_risk_flag"] = True
                diagnostics["risk_notes"].append("Within 1.5% of LOWER CIRCUIT. High fill failure/slippage risk.")

        # Check proximity to upper circuit
        if upper_circuit is not None and upper_circuit > 0:
            dist_upper_pct = (upper_circuit - cmp) / upper_circuit
            diagnostics["distance_to_upper_circuit_pct"] = round(dist_upper_pct * 100, 2)
            if dist_upper_pct <= 0.015:
                diagnostics["near_upper_circuit"] = True
                diagnostics["risk_notes"].append("Within 1.5% of UPPER CIRCUIT. Strong momentum breakout.")

        if not diagnostics["liquidity_passed"]:
            diagnostics["execution_risk_flag"] = True
            diagnostics["risk_notes"].append(f"Turnover ₹{diagnostics['turnover_crores']} Cr < ₹5.0 Cr requirement.")

        return diagnostics

    # ─────────────────────────────────────────────────────────────────────────
    # 3. CIRCUIT-LOCK FALLBACK PROTOCOL
    # ─────────────────────────────────────────────────────────────────────────
    def handle_circuit_lock_fallback(
        self,
        position: Position,
        bar: MarketBar
    ) -> OrderSignal:
        """
        Handles the real-world NSE phenomenon where a stock gaps down limit-locked
        into lower circuit and GTT/SL orders cannot fill.
        Suppresses continuous API cancel loops and queues a pre-market AMO or
        09:15:00 AM limit order for the next trading session.
        """
        logger.warning(
            f"🚨 CIRCUIT LOCK TRIGGERED for {position.symbol} at ₹{bar.cmp:.2f}! "
            f"Suppressing GTT cancellations and queuing AMO / Pre-Market exit."
        )

        position.is_circuit_locked = True
        position.queued_amo = True

        limit_exit_price = bar.lower_circuit if bar.lower_circuit else round(bar.cmp * 0.95, 2)

        return OrderSignal(
            symbol=position.symbol,
            action=OrderAction.AMO_FALLBACK,
            shares=position.current_shares,
            limit_price=limit_exit_price,
            stop_loss=limit_exit_price,
            reason=ExitReason.CIRCUIT_LOCK_STOP,
            urgency="PRE_MARKET_AMO",
            metadata={
                "order_type": "AMO_LIMIT",
                "execution_target": "09:15:00 AM / PRE_MARKET_SESSION",
                "lower_circuit": bar.lower_circuit,
                "notes": "Queued pre-market limit order to ensure front-of-queue priority on circuit unlock."
            }
        )

    # ─────────────────────────────────────────────────────────────────────────
    # 4. STOP LOSS & RATIFIED PROFIT FLOORS EVALUATOR
    # ─────────────────────────────────────────────────────────────────────────
    def evaluate_stop_loss(
        self,
        position: Position,
        bar: MarketBar,
        regime: MacroRegime = MacroRegime.BULL_MARKET
    ) -> Tuple[float, bool, ExitReason]:
        """
        Evaluates active stop-loss level for the current position state.
        Returns: (effective_stop, is_violated, exit_reason)
        """
        # If stock is locked at lower circuit and low == high == lower_circuit
        if bar.lower_circuit and bar.cmp <= (bar.lower_circuit * 1.001) and bar.low == bar.high:
            return bar.cmp, True, ExitReason.CIRCUIT_LOCK_STOP

        effective_stop = position.current_stop

        # State 0: OPEN
        if position.state == TradeState.STATE_0_OPEN:
            # Check if Macro Regime switched to DEFENSIVE_CASH
            if regime == MacroRegime.DEFENSIVE_CASH:
                tightened_stop = round(position.entry_price * 0.96, 2)  # -4% stop
                effective_stop = max(position.current_stop, tightened_stop)
                position.current_stop = effective_stop
                if bar.close <= effective_stop:
                    return effective_stop, True, ExitReason.TIGHTENED_REGIME_STOP
            else:
                if bar.close <= effective_stop:
                    return effective_stop, True, ExitReason.INITIAL_STOP

        # State 1: RISK_FREE (+1.5% Breakeven floor)
        elif position.state == TradeState.STATE_1_RISK_FREE:
            breakeven_floor = round(position.entry_price * (1.0 + self.be_buffer_pct), 2)
            effective_stop = max(position.current_stop, breakeven_floor)
            position.current_stop = effective_stop
            if bar.close <= effective_stop:
                return effective_stop, True, ExitReason.BREAKEVEN_STOP

        # State 2: BANK_AND_TRAIL (+10% Locked Profit floor on 60% runner)
        elif position.state == TradeState.STATE_2_BANK_AND_TRAIL:
            profit_floor = round(position.entry_price * (1.0 + self.runner_stop_floor_pct), 2)
            effective_stop = max(position.current_stop, profit_floor)
            position.current_stop = effective_stop
            if bar.close <= effective_stop:
                return effective_stop, True, ExitReason.LOCKED_PROFIT_STOP

        # State 3: POWER_RUNNER
        elif position.state == TradeState.STATE_3_POWER_RUNNER:
            # Baseline floor remains at least +10%
            profit_floor = round(position.entry_price * (1.0 + self.runner_stop_floor_pct), 2)
            effective_stop = max(position.current_stop, profit_floor)
            position.current_stop = effective_stop
            if bar.close <= effective_stop:
                return effective_stop, True, ExitReason.LOCKED_PROFIT_STOP

        return effective_stop, False, ExitReason.NONE

    # ─────────────────────────────────────────────────────────────────────────
    # 5. PROFIT TARGETS & STATE MACHINE TRANSITIONS
    # ─────────────────────────────────────────────────────────────────────────
    def evaluate_profit_targets(
        self,
        position: Position,
        bar: MarketBar
    ) -> Tuple[Optional[TradeState], Optional[OrderSignal]]:
        """
        Evaluates potential state machine transitions and profit booking actions:
          State 0 -> State 1: PnL hits +12% to +15%
          State 1 -> State 2: PnL hits +20% to +25% (Triggers PARTIAL_PROFIT for 40%)
          State 2 -> State 3: 60% Runner PnL > +25%
        """
        entry = position.entry_price
        cmp = bar.cmp
        unrealized_pnl_pct = (cmp - entry) / entry

        # Update peak price
        if cmp > position.peak_price:
            position.peak_price = cmp

        # ── State 0: OPEN -> State 1: RISK_FREE ──────────────────────────────
        if position.state == TradeState.STATE_0_OPEN:
            if unrealized_pnl_pct >= 0.12:  # Hits +12% to +15%
                new_stop = round(entry * (1.0 + self.be_buffer_pct), 2)
                position.state = TradeState.STATE_1_RISK_FREE
                position.current_stop = new_stop
                logger.info(
                    f"🛡️ {position.symbol} transitioned to RISK_FREE at ₹{cmp:.2f} "
                    f"(+{unrealized_pnl_pct*100:.1f}%). Stop ratcheted to ₹{new_stop:.2f} (+{self.be_buffer_pct*100:.1f}% BE buffer)."
                )
                return TradeState.STATE_1_RISK_FREE, None

        # ── State 1: RISK_FREE -> State 2: BANK_AND_TRAIL ────────────────────
        elif position.state == TradeState.STATE_1_RISK_FREE:
            if unrealized_pnl_pct >= 0.20:  # Hits +20% to +25%
                # Calculate 40% partial exit shares
                shares_to_sell = max(1, math.floor(position.total_shares * self.partial_bank_pct))
                # Ensure we don't sell more than current shares
                shares_to_sell = min(shares_to_sell, position.current_shares)

                # Set new stop for runner position: +10% locked profit
                new_stop = round(entry * (1.0 + self.runner_stop_floor_pct), 2)
                position.state = TradeState.STATE_2_BANK_AND_TRAIL
                position.current_stop = new_stop

                partial_signal = OrderSignal(
                    symbol=position.symbol,
                    action=OrderAction.PARTIAL_PROFIT,
                    shares=shares_to_sell,
                    limit_price=cmp,
                    stop_loss=new_stop,
                    reason="BANK_40PCT_AT_3R",
                    urgency="IMMEDIATE",
                    metadata={
                        "target_achieved_pct": round(unrealized_pnl_pct * 100, 2),
                        "banked_shares": shares_to_sell,
                        "runner_shares": position.current_shares - shares_to_sell,
                        "runner_stop_price": new_stop,
                        "reward_to_risk_ratio": round(unrealized_pnl_pct / max(position.initial_stop_pct, 0.01), 2)
                    }
                )

                logger.info(
                    f"💰 {position.symbol} transitioned to BANK_AND_TRAIL at ₹{cmp:.2f} "
                    f"(+{unrealized_pnl_pct*100:.1f}%). Banking 40% ({shares_to_sell} shares). "
                    f"Runner stop ratcheted to ₹{new_stop:.2f} (+10%)."
                )
                return TradeState.STATE_2_BANK_AND_TRAIL, partial_signal

        # ── State 2: BANK_AND_TRAIL -> State 3: POWER_RUNNER ─────────────────
        elif position.state == TradeState.STATE_2_BANK_AND_TRAIL:
            if unrealized_pnl_pct > 0.25:  # Runner exceeds +25%
                position.state = TradeState.STATE_3_POWER_RUNNER
                logger.info(
                    f"🚀 {position.symbol} transitioned to POWER_RUNNER at ₹{cmp:.2f} "
                    f"(+{unrealized_pnl_pct*100:.1f}%). Ceiling removed! Dynamic 50 SMA / 20 EMA trail active."
                )
                return TradeState.STATE_3_POWER_RUNNER, None

        return None, None

    # ─────────────────────────────────────────────────────────────────────────
    # 6. DYNAMIC TRAILING EXITS FOR STATE 3 (POWER_RUNNER)
    # ─────────────────────────────────────────────────────────────────────────
    def evaluate_power_runner_exits(
        self,
        position: Position,
        bar: MarketBar
    ) -> Tuple[bool, ExitReason, Dict[str, Any]]:
        """
        Evaluates the 3 dynamic trailing exits for State 3:
          1. Primary Trend Exit:
             - Close < rising 50 SMA with Volume > SMA20(Volume)
             - 1-day grace period if volume is below average on day 1; exit on day 2 if unresolved.
             - Immediate exit if 50 SMA itself is curling downward (sma_50 < sma_50_prev).
          2. Short-Term Climax / Mean-Reversion Exit:
             - Close < 20 EMA for high-velocity runs where CMP / 50 SMA > 1.35.
          3. Blow-Off Exhaustion Exit:
             - CMP / 200 SMA > 1.70 AND Daily Range > 3x ATR14 AND Volume == 20-day high.
        """
        meta: Dict[str, Any] = {}

        # ── Exit 3: Blow-Off Exhaustion Exit (Highest priority: sell into peak strength) ──
        dist_sma200 = bar.cmp / bar.sma_200 if bar.sma_200 > 0 else 1.0
        daily_range = bar.high - bar.low
        is_vol_20d_max = bar.volume >= (bar.vol_max_20 * 0.999)

        if (
            dist_sma200 > self.blowoff_sma200_mult
            and daily_range > (self.blowoff_range_atr_mult * bar.atr_14)
            and is_vol_20d_max
        ):
            meta = {
                "exit_rule": "BLOWOFF_EXHAUSTION",
                "dist_sma200": round(dist_sma200, 2),
                "daily_range": round(daily_range, 2),
                "atr_14": round(bar.atr_14, 2),
                "volume": bar.volume,
                "vol_max_20": bar.vol_max_20
            }
            logger.warning(f"🌋 BLOW-OFF EXHAUSTION EXIT triggered for {position.symbol} at ₹{bar.cmp:.2f} into peak volume!")
            return True, ExitReason.BLOWOFF_EXHAUSTION, meta

        # ── Exit 2: Climax / Mean-Reversion Exit ───────────────────────────────
        climax_peak = max(bar.cmp, bar.high, position.peak_price)
        dist_sma50 = climax_peak / bar.sma_50 if bar.sma_50 > 0 else 1.0
        if dist_sma50 > self.climax_extension_mult and bar.close < bar.ema_20:
            meta = {
                "exit_rule": "CLIMAX_EMA20",
                "dist_sma50": round(dist_sma50, 2),
                "ema_20": round(bar.ema_20, 2),
                "close": round(bar.close, 2)
            }
            logger.info(f"⚡ CLIMAX MEAN-REVERSION EXIT triggered for {position.symbol} (Peak/50SMA: {dist_sma50:.2f}x, Close < EMA20).")
            return True, ExitReason.CLIMAX_MEAN_REVERSION_20EMA, meta

        # ── Exit 1: Primary Trend Exit (50 SMA with Grace Period) ─────────────
        is_sma50_rising = bar.sma_50 >= bar.sma_50_prev
        close_below_50sma = bar.close < bar.sma_50
        is_above_avg_vol = bar.volume > bar.vol_sma_20

        if close_below_50sma:
            if not is_sma50_rising:
                # 50 SMA curling downward -> immediate breakdown exit
                meta = {
                    "exit_rule": "PRIMARY_TREND_50SMA_DECLINING",
                    "sma_50": round(bar.sma_50, 2),
                    "sma_50_prev": round(bar.sma_50_prev, 2),
                    "close": round(bar.close, 2)
                }
                logger.info(f"📉 PRIMARY TREND EXIT for {position.symbol}: 50 SMA declining & Close below.")
                return True, ExitReason.PRIMARY_TREND_50SMA, meta

            if is_above_avg_vol:
                # Close below rising 50 SMA with heavy volume -> immediate exit
                meta = {
                    "exit_rule": "PRIMARY_TREND_50SMA_HIGH_VOL",
                    "sma_50": round(bar.sma_50, 2),
                    "volume": bar.volume,
                    "vol_sma_20": round(bar.vol_sma_20, 2)
                }
                logger.info(f"📉 PRIMARY TREND EXIT for {position.symbol}: High volume break below 50 SMA.")
                return True, ExitReason.PRIMARY_TREND_50SMA, meta
            else:
                # Low volume test -> 1-day grace period
                position.days_below_sma50 += 1
                if position.days_below_sma50 >= 2:
                    meta = {
                        "exit_rule": "PRIMARY_TREND_50SMA_GRACE_EXPIRED",
                        "days_below": position.days_below_sma50,
                        "sma_50": round(bar.sma_50, 2)
                    }
                    logger.info(f"⏳ PRIMARY TREND EXIT for {position.symbol}: 1-day grace period expired on 50 SMA violation.")
                    return True, ExitReason.PRIMARY_TREND_50SMA, meta
                else:
                    logger.info(f"🛡️ Grace period Day 1 active for {position.symbol}: Close < 50 SMA on below-average volume.")
        else:
            # Restored above 50 SMA -> reset grace counter
            position.days_below_sma50 = 0

        return False, ExitReason.NONE, meta

    # ─────────────────────────────────────────────────────────────────────────
    # 7. GENERATE ORDER SIGNALS & POSITION LIFECYCLE DISPATCHER
    # ─────────────────────────────────────────────────────────────────────────
    def generate_order_signals(
        self,
        position: Position,
        bar: MarketBar,
        regime: MacroRegime = MacroRegime.BULL_MARKET
    ) -> List[OrderSignal]:
        """
        Main execution dispatcher. Evaluates current bar against stop-loss,
        profit targets, dynamic power runner trailing rules, and circuit safeguards.
        Returns a list of OrderSignals.
        """
        signals: List[OrderSignal] = []

        if position.state == TradeState.STATE_CLOSED or position.current_shares <= 0:
            return signals

        # 1. Circuit Lock Verification
        if bar.lower_circuit and bar.cmp <= (bar.lower_circuit * 1.001) and bar.low == bar.high:
            fallback_signal = self.handle_circuit_lock_fallback(position, bar)
            signals.append(fallback_signal)
            return signals

        # 2. Hard Stop Loss & Ratcheted Profit Floors Evaluation
        effective_stop, is_stop_hit, stop_reason = self.evaluate_stop_loss(position, bar, regime)
        if is_stop_hit:
            exit_signal = OrderSignal(
                symbol=position.symbol,
                action=OrderAction.FULL_CLOSE,
                shares=position.current_shares,
                limit_price=effective_stop,
                stop_loss=effective_stop,
                reason=stop_reason,
                urgency="IMMEDIATE",
                metadata={
                    "state_at_exit": position.state.value,
                    "entry_price": position.entry_price,
                    "exit_price": bar.close,
                    "pnl_pct": round(((bar.close - position.entry_price) / position.entry_price) * 100, 2)
                }
            )
            signals.append(exit_signal)
            position.state = TradeState.STATE_CLOSED
            position.current_shares = 0
            return signals

        # 2b. Fixed-target ROTATION exit (compounding rotation strategy).
        #     When enabled, the entire position is taken off at the fixed target
        #     so the principal + profit can be redeployed into the next ranked
        #     leader. Unlike the two-tier mode, no runner is kept behind.
        if self.rotation_target_pct is not None:
            unrealized = (bar.cmp - position.entry_price) / position.entry_price
            if unrealized >= self.rotation_target_pct:
                rotate_target = round(position.entry_price * (1.0 + self.rotation_target_pct), 2)
                exit_signal = OrderSignal(
                    symbol=position.symbol,
                    action=OrderAction.FULL_CLOSE,
                    shares=position.current_shares,
                    limit_price=rotate_target,
                    stop_loss=rotate_target,
                    reason=ExitReason.ROTATION_TARGET,
                    urgency="IMMEDIATE",
                    metadata={
                        "state_at_exit": position.state.value,
                        "entry_price": position.entry_price,
                        "target_price": rotate_target,
                        "pnl_pct": round(unrealized * 100, 2),
                        "action": "ROTATE_TO_NEXT_LEADER",
                        "rotation_target_pct": round(self.rotation_target_pct * 100, 1),
                    }
                )
                signals.append(exit_signal)
                position.state = TradeState.STATE_CLOSED
                position.current_shares = 0
                return signals

        # 3. Dynamic Power Runner Exits (State 3 Only)
        if position.state == TradeState.STATE_3_POWER_RUNNER:
            is_runner_exit, runner_reason, runner_meta = self.evaluate_power_runner_exits(position, bar)
            if is_runner_exit:
                exit_signal = OrderSignal(
                    symbol=position.symbol,
                    action=OrderAction.FULL_CLOSE,
                    shares=position.current_shares,
                    limit_price=bar.close,
                    stop_loss=bar.close,
                    reason=runner_reason,
                    urgency="IMMEDIATE",
                    metadata={
                        "state_at_exit": position.state.value,
                        "runner_exit_meta": runner_meta,
                        "entry_price": position.entry_price,
                        "exit_price": bar.close,
                        "pnl_pct": round(((bar.close - position.entry_price) / position.entry_price) * 100, 2)
                    }
                )
                signals.append(exit_signal)
                position.state = TradeState.STATE_CLOSED
                position.current_shares = 0
                return signals

        # 4. Profit Target Transitions (State 0 -> 1 -> 2 -> 3)
        new_state, partial_signal = self.evaluate_profit_targets(position, bar)
        if partial_signal:
            signals.append(partial_signal)
            # Deduct shares sold
            position.banked_shares += partial_signal.shares
            position.current_shares -= partial_signal.shares
            realized_gain = (bar.cmp - position.entry_price) * partial_signal.shares
            position.banked_pnl_rupees += realized_gain

        return signals


# ─────────────────────────────────────────────────────────────────────────────
# MATHEMATICAL EDGE & SKEWNESS PROOF SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
def calculate_theoretical_skewness_edge(
    win_rate: float = 0.45,
    avg_loss_pct: float = 0.065,
    fixed_cap_win_pct: float = 0.50,
    multibagger_distribution: Optional[List[Tuple[float, float]]] = None
) -> Dict[str, Any]:
    """
    Computes theoretical expected value E[R], skewness gamma_1, and terminal CAGR
    contrasting a fixed +50% cap vs. an asymmetric two-tier trailing system.
    """
    if multibagger_distribution is None:
        # Distribution of winners in institutional trend-following:
        # 60% of wins: modest +20%
        # 25% of wins: intermediate +50%
        # 10% of wins: multi-bagger +120%
        # 5% of wins: super-performer +250%
        multibagger_distribution = [
            (0.60, 0.20),
            (0.25, 0.50),
            (0.10, 1.20),
            (0.05, 2.50)
        ]

    # 1. Fixed Cap System (All winners capped at +50%, average win ~ 25%)
    # In fixed cap: wins cannot exceed +50%
    wins_fixed = [min(w, fixed_cap_win_pct) for _, w in multibagger_distribution]
    weights = [p for p, _ in multibagger_distribution]
    avg_win_fixed = sum(p * w for p, w in zip(weights, wins_fixed))

    ev_fixed = (win_rate * avg_win_fixed) - ((1.0 - win_rate) * avg_loss_pct)

    # 2. Asymmetric Dynamic Trail System:
    # 40% banked at +22% (+0.088 to portfolio), 60% runner lets full right-tail compound
    # For a winner with move W: total return = 0.40 * 0.22 + 0.60 * W = 0.088 + 0.60 * W
    wins_dynamic = [(0.40 * 0.22 + 0.60 * w) for _, w in multibagger_distribution]
    avg_win_dynamic = sum(p * w for p, w in zip(weights, wins_dynamic))

    ev_dynamic = (win_rate * avg_win_dynamic) - ((1.0 - win_rate) * avg_loss_pct)

    edge_lift_pct = ((ev_dynamic - ev_fixed) / ev_fixed) * 100 if ev_fixed > 0 else 0.0

    return {
        "win_rate_pct": win_rate * 100,
        "avg_loss_pct": avg_loss_pct * 100,
        "fixed_avg_win_pct": round(avg_win_fixed * 100, 2),
        "fixed_expected_return_per_trade_pct": round(ev_fixed * 100, 2),
        "dynamic_avg_win_pct": round(avg_win_dynamic * 100, 2),
        "dynamic_expected_return_per_trade_pct": round(ev_dynamic * 100, 2),
        "expected_edge_lift_pct": round(edge_lift_pct, 1),
        "positive_skewness_unlocked": True
    }
